<a href="https://colab.research.google.com/github/rmshruti3082006/24cs403/blob/main/CIE3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('/content/Iris.csv')
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [9]:
x=df[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
y=df[['Species']]

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=40)

In [11]:
x_train

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
62            6.0           2.2            4.0           1.0
23            5.1           3.3            1.7           0.5
26            5.0           3.4            1.6           0.4
48            5.3           3.7            1.5           0.2
2             4.7           3.2            1.3           0.2
..            ...           ...            ...           ...
71            6.1           2.8            4.0           1.3
12            4.8           3.0            1.4           0.1
50            7.0           3.2            4.7           1.4
7             5.0           3.4            1.5           0.2
70            5.9           3.2            4.8           1.8

[120 rows x 4 columns]

In [12]:
x_test

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
38             4.4           3.0            1.3           0.2
66             5.6           3.0            4.5           1.5
115            6.4           3.2            5.3           2.3
117            7.7           3.8            6.7           2.2
89             5.5           2.5            4.0           1.3
136            6.3           3.4            5.6           2.4
68             6.2           2.2            4.5           1.5
94             5.6           2.7            4.2           1.3
84             5.4           3.0            4.5           1.5
28             5.2           3.4            1.4           0.2
90             5.5           2.6            4.4           1.2
11             4.8           3.4            1.6           0.2
40             5.0           3.5            1.3           0.3
126            6.2           2.8            4.8           1.8
79             5.7           2.6            3.5           1.0
144            6.7           3.3            5.7           2.5
123            6.3           2.7            4.9           1.8
124            6.7           3.3            5.7           2.1
76             6.8           2.8            4.8           1.4
59             5.2           2.7            3.9           1.4
132            6.4           2.8            5.6           2.2
105            7.6           3.0            6.6           2.1
53             5.5           2.3            4.0           1.3
17             5.1           3.5            1.4           0.3
64             5.6           2.9            3.6           1.3
18             5.7           3.8            1.7           0.3
13             4.3           3.0            1.1           0.1
116            6.5           3.0            5.5           1.8
9              4.9           3.1            1.5           0.1
81             5.5           2.4            3.7           1.0

In [13]:
y_train

            Species
62  Iris-versicolor
23      Iris-setosa
26      Iris-setosa
48      Iris-setosa
2       Iris-setosa
..              ...
71  Iris-versicolor
12      Iris-setosa
50  Iris-versicolor
7       Iris-setosa
70  Iris-versicolor

[120 rows x 1 columns]

In [14]:
y_test

             Species
38       Iris-setosa
66   Iris-versicolor
115   Iris-virginica
117   Iris-virginica
89   Iris-versicolor
136   Iris-virginica
68   Iris-versicolor
94   Iris-versicolor
84   Iris-versicolor
28       Iris-setosa
90   Iris-versicolor
11       Iris-setosa
40       Iris-setosa
126   Iris-virginica
79   Iris-versicolor
144   Iris-virginica
123   Iris-virginica
124   Iris-virginica
76   Iris-versicolor
59   Iris-versicolor
132   Iris-virginica
105   Iris-virginica
53   Iris-versicolor
17       Iris-setosa
64   Iris-versicolor
18       Iris-setosa
13       Iris-setosa
116   Iris-virginica
9        Iris-setosa
81   Iris-versicolor

In [24]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [25]:
y_pred=dtc.predict(x_test)
y_pred

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-versicolor'],
      dtype=object)

In [29]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score,f1_score
acc=accuracy_score(y_test,y_pred)
print('accuracy:',acc)
cm=confusion_matrix(y_test,y_pred)
print('confusion_matrix:\n', cm)
pr=precision_score(y_test,y_pred)
print('precision_score:',pr)
sp=recall_score(y_test,y_pred)
print('recall_score',sp)
f1=f1_score(y_test,y_pred)
print('f1_score',f1)

accuracy: 1.0
confusion_matrix:
 [[ 8  0  0]
 [ 0 12  0]
 [ 0  0 10]]

ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].